""" extract asm source from code.json generated by thread-tracing tools """

# Usage:
#   python -m pyhip.exs ck_test/ui_output_agent_40959_dispatch_148/code.json 

import json
import os,sys

from .core.asmtools import prettify

if __name__ == "__main__":
    with open(sys.argv[1]) as f:
        d = json.load(f)

    asm_path = "code-json.s"
    with open(asm_path, "w") as f:
        for code in d["code"]:
            f.write(f"\t{code[0]}\n")

    prettify(asm_path, asm_path)
    print(asm_path)
